// ---------------------------------------------------------------------------
// QuestDay — the Expedition Chronicle (reward CONTENT, not tunables).
//
// When you chart a realm region, your expedition "returns with" a piece of
// knowledge you chose to learn. Each topic is a pool of short, surprising,
// awe-leaning, TRUE entries. Design (research-backed): tease-then-reveal — the
// `teaser` opens a curiosity gap (with a foothold), the `fact` is the payoff.
//
// LICENSING: facts are not copyrightable (Feist v. Rural) — every entry is
// written in original words, seeded from public-domain knowledge and
// fact-checked. The Wisdom pool quotes ONLY public-domain authors. Nothing is
// copied verbatim from Wikipedia/quote sites (CC-BY-SA is viral).
//
// Generated by scripts/gen-chronicle.mjs from the content workflow; a region is
// charted once, so even a single-topic player needs only ~one entry per region.
// Icons are Phosphor names, mapped to components in the view.
// ---------------------------------------------------------------------------

export interface ChronicleEntry {
  id: string
  /** A one-line, gap-opening setup in the expedition's voice (no spoiler). */
  teaser: string
  /** The surprising, true payoff (1–2 sentences, original wording). */
  fact: string
}

export interface ChronicleTopic {
  id: string
  name: string
  /** Phosphor icon name (mapped to a component in the view). */
  icon: string
  blurb: string
  entries: ChronicleEntry[]
}

export const chronicleTopics: ChronicleTopic[] = [
  {
    id: "cosmos",
    name: "Cosmos",
    icon: "Planet",
    blurb: "Stars, space, and the scale of it all",
    entries: [
      { id: "venus-day-longer-than-year", teaser: "Your scouts chart a scorched neighbour-world and find its calendar tangled — here a single spin outlasts the whole orbit…", fact: "Venus turns so slowly that one full rotation takes longer than its entire trip around the Sun. A single rotation runs about 243 Earth-days, while its year is only around 225." },
      { id: "neutron-star-teaspoon", teaser: "The expedition recovers a thimble of matter from a collapsed star — they warn no crew alive could lift it…", fact: "A single teaspoon of neutron-star material would weigh on the order of a billion tons on Earth. The star crams more mass than our entire Sun into a ball roughly the size of a city." },
      { id: "olympus-mons", teaser: "Beyond the red dunes the scouts spot a mountain so vast its summit pierces the thin sky — Everest would be a foothill beside it…", fact: "Olympus Mons on Mars is the tallest known volcano in the solar system, standing roughly two and a half times the height of Mount Everest. It is so broad it would blanket an area about the size of Italy." },
      { id: "seeing-the-sun-in-the-past", teaser: "The astronomers in camp realise the Sun they are sketching is already out of date — they are drawing a memory, not the thing itself…", fact: "Sunlight takes a little over eight minutes to reach Earth, so you always see the Sun as it looked eight minutes ago. The energy in that light spent tens of thousands of years bouncing inside the Sun before it ever escaped its surface." },
      { id: "saturn-floats", teaser: "Your scouts weigh the great ringed giant against a basin of water — and the answer defies every instinct about size…", fact: "Saturn is so light for its size that, given a big enough ocean, the whole planet would float. Its average density is less than water's, because it is mostly hydrogen and helium." },
      { id: "humanity-in-a-sugar-cube", teaser: "A physicist in the party makes an astonishing sketch: every person who ever crowded a city could be squeezed into something you could hold between two fingers…", fact: "Atoms are almost entirely empty space, so if you removed all the gaps from the atoms of every living human, the leftover matter would fit inside a sugar cube. That cube would still weigh as much as the entire human race." },
      { id: "diamond-rain", teaser: "Probing the crushing depths of an ice-giant, the scouts report weather unlike any storm they know — it glitters as it falls…", fact: "Deep inside Neptune and Uranus, immense pressure squeezes carbon into solid diamonds that sink toward the core. Laboratory experiments on Earth have managed to recreate this strange diamond rain." },
      { id: "voyager-farthest-thing", teaser: "The expedition tracks a tiny craft we launched ourselves, now so distant its signal whispers for almost a full day before reaching home…", fact: "Voyager 1, launched in 1977, is the most distant human-made object, now roughly 25 billion kilometres away in interstellar space. It carries a golden record of Earth's music, greetings, and sounds for any traveller who finds it." },
      { id: "more-stars-than-galaxies", teaser: "The night-watch tries to tally every star overhead and quickly realises the number runs past anything they can picture…", fact: "The observable universe holds hundreds of billions of galaxies, and a single galaxy like ours contains hundreds of billions of stars. Multiplied together, the star count climbs into the hundreds of billions of trillions." },
      { id: "tv-static-big-bang", teaser: "Tuning an old receiver between channels, the camp's tinkerer realises a sliver of the hiss is far, far older than any broadcast…", fact: "A small fraction of the snowy static on an old analog TV was the faint afterglow of the Big Bang itself. This ancient microwave glow fills all of space and was stumbled upon by accident in 1965." },
      { id: "andromeda-ancient-light", teaser: "Your scouts point to the farthest smudge the naked eye can catch and note that its light set out before our kind walked the Earth…", fact: "The Andromeda Galaxy is the most distant thing visible to the unaided eye, about 2.5 million light-years away. The light you see from it tonight left before modern humans had even appeared." },
      { id: "iss-sixteen-sunrises", teaser: "The party watches a station racing overhead and learns its crew greets the dawn over and over within a single day…", fact: "Astronauts on the International Space Station see about 16 sunrises and 16 sunsets every day. The station laps the whole planet roughly every 90 minutes, moving near 28,000 kilometres per hour." },
      { id: "moon-footprints", teaser: "On an airless grey world the scouts find old bootprints, pristine — they marvel that nothing has come to disturb them…", fact: "With no wind or weather on the Moon, the footprints left by Apollo astronauts could survive essentially unchanged for millions of years. Only the slow drift of micrometeorite dust will eventually erase them." },
      { id: "silence-of-space", teaser: "The expedition braces for the roar of a distant star and hears nothing at all — the void keeps a perfect, total quiet…", fact: "Space is silent, because sound needs a medium like air to carry it and a vacuum has almost nothing to vibrate. Even the most violent cosmic explosion would make no noise you could hear." },
      { id: "made-of-stardust", teaser: "Studying the ash of a long-dead star, the scouts trace a thread that leads, impossibly, back to the crew's own bones…", fact: "Nearly every element heavier than hydrogen — the iron in your blood, the calcium in your bones, the oxygen you breathe — was forged inside stars and scattered when they died. We are quite literally made of ancient stardust." },
      { id: "galaxies-faster-than-light", teaser: "The astronomers chart the most distant galaxies fleeing the camp's view and find they outrun the one thing thought to be unbeatable…", fact: "The most distant galaxies recede from us faster than the speed of light — not by moving through space, but because space itself is stretching between us. The cosmic speed limit applies to motion through space, not to space's own expansion." },
      { id: "gps-time-dilation", teaser: "Comparing two perfect clocks — one in camp, one carried high above — the scouts find them quietly disagreeing about the time…", fact: "Clocks on GPS satellites tick faster than clocks on the ground because gravity is weaker up high — by about 38 millionths of a second a day. Navigation would drift miles off course daily if engineers didn't correct for this slip in time." }
    ]
  },
  {
    id: "nature",
    name: "Nature & Earth",
    icon: "Leaf",
    blurb: "The living world and the planet beneath it",
    entries: [
      { id: "tardigrade-vacuum", teaser: "Your scouts find a speck of moss by the trail, and inside it something that laughs at the void above…", fact: "The tardigrade, a near-microscopic eight-legged animal, is the only creature known to survive the raw vacuum of open space. On a 2007 orbital mission, dried-out specimens were exposed directly to space and many revived once back on Earth." },
      { id: "octopus-three-hearts", teaser: "An expedition to the tide pools reports a hunter whose body breaks one rule of how a heart should work…", fact: "An octopus has three hearts and blue blood that ferries oxygen using copper instead of iron. The main heart that feeds its body actually stops beating whenever it swims, which is partly why many octopuses prefer to crawl." },
      { id: "greenland-shark-age", teaser: "From the cold deep waters, your scouts bring word of a fish that may have been alive before your great-great-grandparents…", fact: "The Greenland shark is the longest-lived vertebrate known, reaching roughly 400 years of age. It grows so slowly that it does not even reach maturity until it is around 150 years old." },
      { id: "sharks-older-than-trees", teaser: "Studying fossils in the cliffs, your scholars realise the order of the world is older and stranger than the maps suggest…", fact: "Sharks have patrolled the oceans for over 400 million years, meaning they predate the first trees — and even Saturn's rings, which formed surprisingly recently. They have survived every mass extinction since." },
      { id: "pando-aspen", teaser: "Your scouts walk through a vast grove of trembling golden trees and slowly grasp that they are standing inside ONE creature…", fact: "A grove of around 47,000 aspen trunks in Utah, called Pando, is actually a single organism sharing one connected root system. By weight it is among the heaviest living things on Earth, and it may be tens of thousands of years old." },
      { id: "bristlecone-methuselah", teaser: "High on a windswept ridge your scouts kneel before a gnarled tree that was already ancient when the pyramids were new…", fact: "A Great Basin bristlecone pine nicknamed Methuselah has been alive for roughly 4,800 years. It sprouted before the Egyptian pyramids were built and is still growing today." },
      { id: "ocean-oxygen", teaser: "Sailing past the open sea, your scouts wonder which forest truly keeps the world breathing — and the answer has no trees at all…", fact: "Roughly half of all the oxygen on Earth is produced by tiny ocean drifters called phytoplankton, not by forests. Much of the air you breathe traces back to microscopic life floating in the sea." },
      { id: "stomach-relining", teaser: "Your camp's healer studies how a body can hold acid strong enough to corrode metal without dissolving itself…", fact: "Your stomach holds acid potent enough to corrode metal, so to keep from digesting itself it grows a fresh inner lining roughly every few days. You are constantly rebuilding the wall that protects you." },
      { id: "red-blood-cells", teaser: "The healer counts heartbeats and realises an unseen factory inside you never once pauses, day or night…", fact: "Your body manufactures around two and a half million new red blood cells every single second. In the time it took to read this sentence, you made many millions more." },
      { id: "body-microbes", teaser: "Your scholars ask a simple question — how much of 'you' is actually you — and the count comes back unsettlingly close…", fact: "Your body holds roughly as many bacterial cells as human cells — about 38 trillion microbes to 30 trillion of your own. You are very nearly half microbe by cell count, and most of them help keep you healthy." },
      { id: "axolotl-regeneration", teaser: "An expedition to a misty lake finds a smiling amphibian that heals wounds no other backboned creature can…", fact: "The axolotl, a perpetually youthful salamander, can fully regrow lost limbs, parts of its heart, its spinal cord, and even portions of its brain — all without scarring. Scientists study it hoping to unlock human healing." },
      { id: "wombat-cubes", teaser: "Your trackers find perfectly squared droppings on a log and refuse to believe an animal could shape such a thing…", fact: "The wombat is the only animal known to produce cube-shaped droppings, formed by stiff and stretchy zones inside its intestines. The flat sides keep the cubes from rolling away when used to mark territory." },
      { id: "mantis-shrimp-eyes", teaser: "In a reef crevice your scouts meet a small crustacean that may see a layer of light hidden from every other eye on Earth…", fact: "The mantis shrimp has a dozen or more types of colour receptor — humans have three — and is the only animal known to detect circularly polarized light. It perceives a dimension of light completely invisible to us." },
      { id: "flamingo-pink", teaser: "Your scouts watch a flock of rose-coloured birds and learn their famous hue was not theirs to begin with…", fact: "Flamingos hatch grey, not pink. Their rosy colour is borrowed entirely from pigments in the algae and tiny shrimp they eat, and a flamingo cut off from that diet would slowly fade back toward pale." },
      { id: "mauna-kea-tallest", teaser: "Charting the peaks, your surveyors discover the true giant of mountains hides most of itself beneath the waves…", fact: "Measured from its base on the seafloor to its summit, Hawaii's Mauna Kea is taller than Mount Everest, standing over 10,000 metres in total. More than half of it is simply hidden underwater." },
      { id: "wood-wide-web", teaser: "Beneath the forest floor your scouts uncover a hidden web that lets trees trade and pass messages to one another…", fact: "Forest trees are linked underground by vast networks of fungal threads, nicknamed the 'wood wide web,' through which they can share nutrients and warning signals. Older trees can even funnel sugar to shaded young saplings." },
      { id: "lightning-strikes", teaser: "During a storm your scouts try to tally the flashes over the whole world and quickly lose count…", fact: "At any given moment thousands of thunderstorms are crackling across the planet, adding up to millions of lightning strikes every single day. Dozens of bolts are firing somewhere on Earth every second." }
    ]
  },
  {
    id: "history",
    name: "History",
    icon: "Scroll",
    blurb: "Surprising truths from the ages",
    entries: [
      { id: "cleopatra-moon-landing", teaser: "Your scouts chart the great stone tombs of the Nile and bring back a riddle of time itself: the queen most tied to these monuments lived nowhere near the hands that raised them.", fact: "Cleopatra ruled Egypt around 30 BC, but the Great Pyramid was already roughly 2,500 years old by her day. She actually lived closer in time to the first Moon landing than to the building of that pyramid." },
      { id: "mammoths-and-pyramids", teaser: "Far to the frozen north, your expedition finds tusks in the permafrost and returns with a date that refuses to sit where you'd expect it.", fact: "A last herd of woolly mammoths survived on remote Wrangel Island until about 1650 BC. By then the Great Pyramid of Giza had already stood for nearly a thousand years." },
      { id: "oxford-older-than-aztecs", teaser: "Two distant lands, two famous names — your scribes line up their founding dates and the order comes out backwards from what everyone assumes.", fact: "Teaching at Oxford had been going on since at least 1096, while the Aztec capital Tenochtitlan wasn't founded until 1325. Oxford was already over two centuries old before that city existed." },
      { id: "roman-concrete-self-heals", teaser: "Along a crumbling sea wall your engineers test ancient harbour stone — and report the impossible: the saltwater isn't wearing it down, it's making it stronger.", fact: "Roman concrete contains tiny lumps of lime that dissolve when water seeps into a crack and re-crystallize to seal it, so the material can heal itself. In seawater, new minerals even grow inside it, strengthening it over centuries." },
      { id: "antikythera-mechanism", teaser: "Divers return from a wrecked Greek ship with a corroded bronze lump full of tiny teeth — and the engineers swear it's a machine far ahead of its age.", fact: "The Antikythera mechanism is a hand-cranked bronze device from around 100 BC with dozens of precision gears that predicted eclipses and tracked the Sun, Moon, and planets. Nothing of comparable complexity is known again for well over a thousand years." },
      { id: "vikings-exact-year-1021", teaser: "A burst of light in the ancient sky left its fingerprint in tree rings — and your scouts say it pins down a Norse camp in the New World to a single, exact year.", fact: "A cosmic radiation surge in AD 993 left a spike in tree rings worldwide. By counting the rings in wood that Norse settlers cut at L'Anse aux Meadows in Newfoundland, researchers dated their presence in North America to exactly AD 1021 — five centuries before Columbus." },
      { id: "pyramid-tallest-3800-years", teaser: "Your surveyors measure the Great Pyramid against every spire raised since, and the tally of years it reigned over the skyline stops you cold.", fact: "The Great Pyramid of Giza was the tallest structure built by human hands for nearly 3,800 years. Its record stood until Lincoln Cathedral's great spire rose in England around 1311." },
      { id: "lighthouse-of-alexandria", teaser: "Among the wonders your expedition catalogs, one giant of the harbour turns out to have outlasted almost all its legendary peers.", fact: "The Lighthouse of Alexandria, one of the Seven Wonders of the Ancient World, guided ships for well over a thousand years, and its ruins lingered into the late 1400s. Of the seven wonders, only the Great Pyramid has endured longer." },
      { id: "polar-bear-in-thames", teaser: "Your scouts hear an old London tale of a white beast on a long rope, plunging into the river to fish — and find it's no fable at all.", fact: "In the 1250s the Tower of London kept a royal menagerie, and a polar bear gifted by the King of Norway was led on a chain to the River Thames to swim and catch fish. Crowds gathered on the banks just to watch." },
      { id: "babylon-copper-complaint", teaser: "Among the baked clay tablets of an old trading town, your translators uncover a furious message that feels eerily modern.", fact: "A clay tablet from around 1750 BC in the city of Ur is an angry complaint from a customer named Nanni to a copper merchant called Ea-nasir about poor-quality goods and rude service. It is recognized as the oldest known written customer complaint." },
      { id: "honey-never-spoils", teaser: "Sealed deep in an ancient tomb, your scouts find sealed jars — and the keeper insists what's inside could still be eaten today.", fact: "Honey sealed in Egyptian tombs over 3,000 years ago has been found still edible. Its very low water content, natural acidity, and a bee-made trace of hydrogen peroxide make it nearly impossible for microbes to grow." },
      { id: "pyramid-builders-paid", teaser: "Near the great tombs your expedition uncovers the builders' own graves and ration records, overturning the story everyone tells about who raised them.", fact: "The Great Pyramid was built by organized crews of paid, skilled workers — not slaves. They were given rations of bread and beer, and the most honoured were buried in their own tombs beside the pyramids they built." },
      { id: "pompeii-graffiti", teaser: "On the buried walls of a Roman town, your scouts copy down thousands of scratched messages — and find the ancient world chattering exactly like ours.", fact: "More than 11,000 pieces of graffiti survive on the walls of Pompeii: election slogans, love notes, jokes, and idle boasts left by ordinary people. They reveal that everyday Romans gossiped and complained much as we do today." },
      { id: "hurrian-oldest-melody", teaser: "Your scribes recover a clay tablet covered in wedge-shaped marks — and realize it isn't a list or a letter, but a song that can still be played.", fact: "A clay tablet found in ancient Ugarit preserves the Hurrian Hymn, a tune for voice and lyre that is about 3,400 years old. It is the oldest substantially complete piece of written music known to exist." },
      { id: "newgrange-solstice", teaser: "In a green northern land, your scouts enter a grass-covered stone mound and discover it was built to capture a single sunrise each year.", fact: "Newgrange in Ireland is a stone passage tomb built around 3200 BC — older than Stonehenge and the Great Pyramid. Each winter solstice, sunrise light slides through a special opening and floods its inner chamber for about 17 minutes." },
      { id: "nintendo-eiffel-tower", teaser: "Tracing the lineage of a famous game-making house, your historians land on a founding year it shares with one of the world's most iconic towers.", fact: "Nintendo was founded in 1889 — the same year the Eiffel Tower was completed — as a maker of hand-painted playing cards. It sold cards for the better part of a century before it ever made a video game." }
    ]
  },
  {
    id: "wisdom",
    name: "Timeless Wisdom",
    icon: "Feather",
    blurb: "Maxims that have outlasted empires",
    entries: [
      { id: "aurelius-obstacle-is-the-way", teaser: "Your scouts find a line scratched into the stone of a blocked mountain pass — a soldier-emperor's note on what to do when the road is barred.", fact: "\"The impediment to action advances action. What stands in the way becomes the way.\" — Marcus Aurelius, Meditations, Book 5" },
      { id: "seneca-imagination-suffering", teaser: "From a Roman tutor's letters the expedition copies one sentence about fear — and it claims most of our pain never actually arrives.", fact: "\"There are more things that frighten us than injure us, and we suffer more often in imagination than in reality.\" — Seneca, Moral Letters to Lucilius, Letter 13" },
      { id: "laozi-thousand-li-beneath-feet", teaser: "A worn signpost at the trailhead carries an old Taoist line — and the literal Chinese names where every long journey truly starts.", fact: "\"A journey of a thousand li begins beneath one's feet.\" — Lao Tzu, Tao Te Ching, Chapter 64 (the original 始於足下 means \"begins beneath the feet,\" i.e. right where you already stand)" },
      { id: "laozi-master-yourself", teaser: "Your scouts trade with a hermit who offers one riddle about strength versus power — and quietly turns it inward.", fact: "\"Mastering others is strength; mastering yourself is true power.\" — Lao Tzu, Tao Te Ching, Chapter 33" },
      { id: "aurelius-best-revenge", teaser: "Among an emperor's private notes the expedition finds the shortest possible answer to being wronged.", fact: "\"The best revenge is not to be like your enemy.\" — Marcus Aurelius, Meditations, Book 6" },
      { id: "seneca-life-is-a-play", teaser: "A philosopher's letter compares a whole human life to a single thing the scouts recognise from the camp's evening entertainments.", fact: "\"It is with life as it is with a play — it matters not how long the action is spun out, but how good the acting is.\" — Seneca, Moral Letters to Lucilius, Letter 77" },
      { id: "epictetus-judgments-disturb", teaser: "A former slave turned teacher hands the expedition one idea about why the same event ruins one traveller and barely touches another.", fact: "\"People are disturbed not by things, but by the judgments they form about things.\" — Epictetus, Enchiridion, 5" },
      { id: "confucius-know-what-you-dont-know", teaser: "Carved on a teacher's gate the scouts find a definition of real knowledge — and it includes knowing what you do NOT know.", fact: "\"When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it — this is knowledge.\" — Confucius, Analects, 2.17" },
      { id: "seneca-postponing-life", teaser: "The very first letter in a Roman collection warns the expedition about the one possession no one can ever get back.", fact: "\"While we are postponing, life speeds by.\" — Seneca, Moral Letters to Lucilius, Letter 1 (Latin: \"Dum differtur vita transcurrit\")" },
      { id: "laozi-best-leader", teaser: "An old chronicle describes the very best ruler the scouts could serve — and the strange thing the people say once the work is done.", fact: "\"When the best leader's work is done, the people say: We did it ourselves.\" — Lao Tzu, Tao Te Ching, Chapter 17" },
      { id: "aurelius-be-good", teaser: "An emperor cuts off his own philosophizing mid-thought with a blunt command to himself.", fact: "\"Waste no more time arguing what a good man should be. Be one.\" — Marcus Aurelius, Meditations, Book 10" },
      { id: "laozi-water", teaser: "A Taoist verse names the highest goodness — and likens it to the most ordinary, lowest-flowing thing the scouts fill their flasks with.", fact: "\"The highest good is like water: it benefits all things and does not contend, dwelling in the lowly places that all disdain.\" — Lao Tzu, Tao Te Ching, Chapter 8" },
      { id: "epictetus-up-to-us", teaser: "A handbook for living opens by dividing the entire world into two piles — and almost everything lands in the pile you can't touch.", fact: "\"Some things are within our power, and some are not.\" — Epictetus, Enchiridion, 1 (the famous opening that begins Stoicism's dichotomy of control)" },
      { id: "aurelius-happy-life-within", teaser: "An emperor who ruled half the known world wrote down how little it actually takes to be happy — and where it's hidden.", fact: "\"Very little is needed to make a happy life; it is all within yourself, in your way of thinking.\" — Marcus Aurelius, Meditations, Book 7" },
      { id: "laozi-enough-is-rich", teaser: "A single line in a Taoist text redefines wealth — and it has nothing to do with how much gold rides in the caravan.", fact: "\"He who knows he has enough is rich.\" — Lao Tzu, Tao Te Ching, Chapter 33" },
      { id: "confucius-learning-and-thought", teaser: "A teacher's maxim warns the expedition that books and pondering each fail on their own — and pairs them.", fact: "\"Learning without thought is labour lost; thought without learning is perilous.\" — Confucius, Analects, 2.15" }
    ]
  },
]

export function topicById(id: string): ChronicleTopic | undefined {
  return chronicleTopics.find((t) => t.id === id)
}

export function entryById(topicId: string, entryId: string): ChronicleEntry | undefined {
  return topicById(topicId)?.entries.find((e) => e.id === entryId)
}
